config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'sales#index'

  resources :sales
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
  validates :name, presence: true, uniqueness: true

  has_many :orders
  has_many :items, through: :orders, class_name: 'Order::Item'
end

app/models/merchant.rb
class Merchant < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  validates :address, presence: true

  has_many :products

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  belongs_to :sale

  has_many :items
end

app/models/order/item.rb
class Order::Item < ApplicationRecord
  belongs_to :order
  belongs_to :product

  delegate :customer, to: :order
end

app/models/product.rb
class Product < ApplicationRecord
  validates_uniqueness_of :description, scope: [:merchant_id, :price]

  validates :description, presence: true
  validates :merchant_id, presence: true

  belongs_to :merchant
end

app/models/sale.rb
class Sale < ApplicationRecord
  has_many :orders
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  include SalesHelper

  before_action :check_file, only: :create

  def index
    Presenters::Sales::Index
      .call
      .on_success do |result|
        @sales = result.data[:sales]
        @total_gross_income = result.data[:total_gross_income]
        @mean_avg_per_sale = result.data[:mean_avg_per_sale]
        @best_seller = result.data[:best_seller]
        @top_buyer = result.data[:top_buyer]
      end
  end

  def show
    Presenters::Sales::Show
      .call(sale_id: params[:id])
      .on_success do |result|
        @sale = result.data[:sale]
        @orders = result.data[:orders]
        @sale_income = result.data[:sale_income]
        @average_ticket = result.data[:average_ticket]
        @featured_product = result.data[:featured_product]
        @top_buyer = result.data[:top_buyer]
      end
  end

  def create
    SalesReport::Collect
      .call(raw: extracted_data)
      .on_success { |result| flash[:success] = [success_msg(result.data[:sale].orders.count)] }
      .on_failure { |result| flash[:alert] = result.data[:errors].map { |error| error_msg(error) } }
      .then do |result|
        return redirect_to sales_path if result.success?

        redirect_to new_sale_path
      end
  end

  private

  def sales_params
    params.require(:report_file)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class
    {
      'notice' => 'alert alert-info',
      'success' => 'alert alert-success',
      'error' => 'alert alert-danger',
      'alert' => 'alert alert-danger'
    }
  end
end

app/helpers/sale_helper.rb
module SaleHelper
end

app/helpers/sales_helper.rb
module SalesHelper
  def success_msg(amount_created)
    {
      title: 'Sucesso!',
      description: "Venda com #{amount_created} pedidos cadastrada!"
    }
  end

  def error_msg(hash_error)
    {
      title: hash_error[:type],
      info: "Linha #{(hash_error[:line] || 0) + 1}, Coluna #{(hash_error[:column] || 0) + 1}",
      description: <<-TEXT
                  Esperava: #{hash_error[:expected]}.
                  Recebeu: #{hash_error[:value]}
      TEXT
    }
  end

  def readable?(file)
    file_type, status = Open3.capture2e('file', file.path)
    status.success? && file_type.include?('text')
  end

  def report_file
    sales_params.open
  end

  def extracted_data
    @extracted_data ||= report_file.read
  end

  def check_file
    return if readable? report_file

    flash[:error] = [error_msg(type: 'Invalid file type', expected: 'Arquivo de texto', value: 'Binário')]
    redirect_to new_sale_path
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Backoffice</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container-fluid overflow-hidden">
      <div class="row vh-100 overflow-auto">
        <%= render 'shared/sidebar' %>
        <div class="col d-flex flex-column h-100">
          <main class="row">
            <%= render 'shared/flash_message' %>
            <%= yield %>
          </main>
          <footer class="row bg-light py-4 mt-auto">
            <div class="col"> Bottom footer content here... </div>
          </footer>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/sales/index.html.erb
<h2 class="display-3">Relatório Geral de Vendas</h2>
<div class="card-group container-fluid content-row">
  <div class="card text-white bg-primary mb-3 col" style="max-width: 20rem;">
    <div class="card-header">Rendimentos Brutos Totais</div>
    <div class="card-body">
      <h2 class="card-title"><%= number_to_currency(@total_gross_income, unit: "R$", separator: ",", delimiter: ".") %></h2>
    </div>
  </div>
  <div class="card text-white bg-secondary mb-3 col" style="max-width: 20rem;">
    <div class="card-header">Média por Venda</div>
    <div class="card-body">
      <h2 class="card-title"><%= number_to_currency(@mean_avg_per_sale, unit: "R$", separator: ",", delimiter: ".") %></h2>
    </div>
  </div>
    <div class="card text-white bg-primary mb-3 col" style="max-width: 20rem;">
    <div class="card-header">Top Comprador</div>
    <div class="card-body">
      <h3 class="card-title"><%= @top_buyer[:name] %></h2>
      <h4 class="card-text"><%= number_to_currency(@top_buyer[:value], unit: "R$", separator: ",", delimiter: ".") %></h4>
    </div>
  </div>
    <div class="card text-white bg-secondary mb-3 col" style="max-width: 20rem;">
    <div class="card-header">Top Vendedor</div>
    <div class="card-body">
      <h3 class="card-title"><%= @best_seller[:name] %></h2>
      <h4 class="card-text"><%= number_to_currency(@best_seller[:value], unit: "R$", separator: ",", delimiter: ".") %></h4>

    </div>
  </div>
</div>
<h2>Lista de vendas</h2>
<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Date</th>
      <th scope="col">Uploaded by</th>
    </tr>
  </thead>
  <tbody>
  <% @sales.each do |sale|%>
    <tr onclick="window.location='<%= sale_url(sale.id) %>';">
        <th scope="row"><%= sale.id %></th>
        <td><%= sale.created_at.strftime("%c") %></td>
        <td>@mdo</td>
      </a>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/sales/new.html.erb
<section class="py-5 text-center container">
  <div class="row py-lg-5">
      <%= form_with url: sales_path, method: :post do |form| %>
        <%= form.label :sales, "Vendas consolidadas" %>
        <div class="form-group">
          <%= form.file_field :report_file, required: true, class: "form-control-file" %>
          <%= form.submit "Enviar" %>
        </div>
      <% end %>
  </div>
</section>

app/views/sales/show.html.erb
<h2 class="display-3">Relatório Geral de Vendas</h2>
<div class="card-group container-fluid content-row">
  <div class="card text-white bg-primary mb-3 col" style="max-width: 20rem;">
    <div class="card-header">Valor Total</div>
    <div class="card-body">
      <h2 class="card-title"><%= number_to_currency(@sale_income, unit: "R$", separator: ",", delimiter: ".") %></h2>
    </div>
  </div>
  <div class="card text-white bg-secondary mb-3 col" style="max-width: 20rem;">
    <div class="card-header">Ticket médio</div>
    <div class="card-body">
      <h2 class="card-title"><%= number_to_currency(@average_ticket, unit: "R$", separator: ",", delimiter: ".") %></h2>
    </div>
  </div>
    <div class="card text-white bg-primary mb-3 col" style="max-width: 20rem;">
    <div class="card-header">Top Produto</div>
    <div class="card-body">
      <h3 class="card-title"><%= @featured_product[:name] %></h2>
      <h4 class="card-text"><%= number_to_currency(@featured_product[:value], unit: "R$", separator: ",", delimiter: ".") %></h4>
    </div>
  </div>
    <div class="card text-white bg-secondary mb-3 col" style="max-width: 20rem;">
    <div class="card-header">Top Comprador</div>
    <div class="card-body">
      <h3 class="card-title"><%= @top_buyer[:name] %></h2>
      <h4 class="card-text"><%= number_to_currency(@top_buyer[:value], unit: "R$", separator: ",", delimiter: ".") %></h4>

    </div>
  </div>
</div>
<h2>Lista de Pedidos</h2>
<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Ordenante</th>
      <th scope="col">Valor</th>
    </tr>
  </thead>
  <tbody>
  <% @orders.each do |order|%>
    <tr>
      <th scope="row"><%= order[:id] %></th>
      <td><%= order[:customer] %></td>
      <td><%= number_to_currency(order[:final_value],  unit: "R$", separator: ",", delimiter: ".") %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/shared/_flash_message.html.erb
<% flash.each do |type, messages| %>
  <% messages.each do |message|  %>
    <div class="<%= flash_class[type] %>" role="alert">
      <h5><%= message["title"] %> </h5>
      <p><sub><%= message["info"] %><sub></p>
      <p><%= message["description"] %></p>
    </div>
  <% end %>
<% end %>

app/views/shared/_sidebar.html.erb
<div class="col-12 col-sm-3 col-xl-2 px-sm-2 px-0 bg-dark d-flex sticky-top">
    <div class="d-flex flex-sm-column flex-row flex-grow-1 align-items-center align-items-sm-start px-3 pt-2 text-white">
        <a href="/" class="d-flex align-items-center pb-sm-3 mb-md-0 me-md-auto text-white text-decoration-none">
            <span class="fs-5">B<span class="d-none d-sm-inline">ackoffice</span></span>
        </a>
        <ul class="nav nav-pills flex-sm-column flex-row flex-nowrap flex-shrink-1 flex-sm-grow-0 flex-grow-1 mb-sm-auto mb-0 justify-content-center align-items-center align-items-sm-start" id="menu">
            <li class="nav-item">
                <a href="<%= sales_path %>" class="nav-link px-sm-0 px-2">
                    <i class="fs-5 bi-house"></i><span class="ms-1 d-none d-sm-inline">Relatório</span>
                </a>
            </li>
            <li>
                <a href="<%= new_sale_path %>" data-bs-toggle="collapse" class="nav-link px-sm-0 px-2">
                <i class="fs-5 bi-speedometer2"></i><span class="ms-1 d-none d-sm-inline">Cadastrar venda</span> </a>
            </li>
        </ul>
    </div>
</div>